[package]
name = "functions"
version = "0.1.0"
authors = ["David Roman <david.roman@ubisoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
